### ISSUE TITLE
Attendees+Volunteer/Roles Page

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-django#5]
### **This issue now only consists of tasks 6-12.**

- [ ] 1- Include Volunteer roles on attendance page. **(moved to #96)**
- [ ] 2- Add the hours required for each role **(moved to #97)**
- [ ] 3- Hours required should default as the same hours for the entire event and be able to be changed for each role **(moved to #97)**
- [ ] 4- "Add Role" Button at bottom of first role description (and subsequent ones) that adds another title/description/start-end/min+max volunteers Role **(moved to #96)**
- [ ] 5- Add text at the bottom of the description and just before the Add Role button: "Will all of the volunteers have the same role? If not, be sure to click [Add Role] **(moved to #96)**

---

- [x] 6- Add descriptive text for Role title in grey: "What should this group of volunteers be called?"

![image](https://user-images.githubusercontent.com/5350076/43149187-de98e054-8f34-11e8-83e2-a6672696e5ea.png)

- [x] 7- Add descriptive text in Role description in grey: "A more detailed description will help your volunteers be better prepared."

![image](https://user-images.githubusercontent.com/5350076/43149213-ee3c9e38-8f34-11e8-9e8a-14ec00278ace.png)

 - [x] 8- Replace text for minimum volunteers "For this activity to happen, what is the minimum amount of volunteers required to fill this specific role?"

![image](https://user-images.githubusercontent.com/5350076/43149253-04b8af8a-8f35-11e8-83cd-2856d490b918.png)

- [x]  9- Replace text for ideal amount of volunteers "For this this activity to be even better, what is the maximum amount of volunteers for this specific role?"

![image](https://user-images.githubusercontent.com/5350076/43149277-1211a100-8f35-11e8-87b0-26215d789887.png)

- [x] 10- Place "For this activity to happen, what is the minimum amount of volunteers required to fill this specific role?" option before "For this this activity to be even better, what is the maximum amount of volunteers for this specific role?"

![image](https://user-images.githubusercontent.com/5350076/43149351-3b6fee3a-8f35-11e8-8e2b-043db9a35180.png)

- [x] 11- When a user puts a number in the minimum amount of volunteers, have the optimal number increase accordingly. If the user then lowers the minimum amount of volunteers, the optimal amount will not lower. This is how attendees numbers currently function, so look at that code.

![image](https://user-images.githubusercontent.com/5350076/43149487-8768c096-8f35-11e8-8b44-f24d511c5656.png)

- [x] 12- Disallow users to input non-numbers into number fields. Currently a user can create a non-number and still move forward in the activity creation process.

![37409002_10100871524784624_8510138592176111616_n](https://user-images.githubusercontent.com/5350076/42967543-93d24e9e-8b6e-11e8-8d4d-c1172778acf1.png)

**Comment by samiriaz135** [comment]
Done with issue-05 sub-issue 6-10 and 12. Will probably need some help with sub-issue 11
